# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем скрипт в рабочую директорию
COPY script.py .

# Устанавливаем команды для запуска
CMD ["python", "script.py"]