apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/f0xx21/K8s.git'
    targetRevision: HEAD
    path: '/home/fox/Downloads/other/K8s/victoria/overlays/production'
  destination:
    server: 'https://github.com/f0xx21/K8s/tree/main/argocd'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true