apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
  source:
    helm:
      valueFiles: []
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: promtail
    targetRevision: 6.16.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true